[build]
cmd = 'npm run railway:build'

[start]
cmd = 'npm start'

[variables]
NODE_ENV = 'production'
CRON_ENABLED = 'true'

[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm-9_x']

[phases.install]
cmd = 'npm ci'

[phases.build]
cmd = 'npm run build'
